=== OpenCoralTools/oct-registry/public/schemas/genets.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Genet",
    "version": "0.0.1",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "minLength": 1,
            "description": "Unique genet identifier"
        },
        "orgId": {
            "type": "string",
            "minLength": 1,
            "description": "ID of the organization managing this genet"
        },
        "speciesCode": {
            "type": "string",
            "minLength": 4,
            "maxLength": 4,
            "description": "Species code of this genet"
        },
        "notes": {
            "type": "string",
            "description": "Additional notes"
        },
        "_schemaVersion": {
            "type": "string",
            "description": "The schema version used when this record was created/updated",
            "readOnly": true
        }
    },
    "required": [
        "id",
        "orgId",
        "speciesCode"
    ],
    "additionalProperties": false
}

=== OpenCoralTools/oct-registry/data/genets.json
[
    {
        "id": "apal-123",
        "orgId": "oct",
        "speciesCode": "APAL",
        "notes": "Example genet",
        "_schemaVersion": "0.0.1"
    },
    {
        "id": "acer-456",
        "orgId": "oct",
        "speciesCode": "ACER",
        "notes": "Example genet",
        "_schemaVersion": "0.0.1"
    }
]
